### ISSUE TITLE
Linke to my data in feather format

### ISSUE THREAD

**Issue by bobaekang** [bobaekang/MA_thesis#1]
@bensoltoff 
In [this Google Drive folder](https://drive.google.com/open?id=0BwAUJb6-KtheX2JfSXVSWUNtV1k), I have put all the data outputs in feather format I have produced with my scripts. I will continue updating it whenever I produce more .feather outputs.

**Comment by bensoltoff** [comment]
You need to grant me permission to access it. Share the folder with ben@bensoltoff.com
